version: "3"

services:
  workspace:
    build: workspace
    working_dir: "/workspace/"
    command: >
      bash -c "pip install -r /workspace/app/requirements.txt && sleep infinity"
    volumes:
      - ../:/workspace/
