version: '3'
services:
  app:
    build: ./app
    container_name: "cw-map-editor"
    working_dir: "/app/"
    tty: true
    volumes:
      - ./app:/app/
      - ../src/main/resources/map:/dist/
      - ../src/main/resources/textures:/app/client/public/resources/textures/
    ports:
      - 8080:8080
    command: "python3 src/app.py"
  client:
    build: ./app/client
    container_name: "cw-map-editor-client"
    working_dir: "/client/"
    volumes:
      - ./app/client:/client/
    command: "/bin/bash -c 'yarn install --frozen-lockfile && yarn dev'"
    environment:
      - CHOKIDAR_USEPOLLING=1