.PHONY: up
up:
	docker-compose up

.PHONY: build-up
build-up:
	docker-compose build
	make up

.PHONY: exec-app
exec:
	docker-compose exec app /bin/bash

.PHONY: exec-client

.PHONY: down
down:
	docker-compose down
